import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { auditSummary, escapeCsv, formatDuration, sanitizeCsvCell } from "../lib/admin/format.ts";
import { labDateTimeToIso, labDayBounds } from "../lib/timezone.ts";
import { mapBookingError } from "../lib/bookings/errors.ts";
import { validateInstrument, validateRoleChange } from "../lib/admin/validation.ts";

test("instrument validation accepts operational data and rejects unsafe URLs", () => { const valid = validateInstrument({ name: "PPMS", description: "Low-temperature measurements", location: "Lab A12", manager: "Dr. Chen", status: "available", imageUrl: "https://example.edu/ppms.jpg" }); assert.ok(valid.value); const invalid = validateInstrument({ name: "P", description: "", location: "X", manager: "Y", status: "available", imageUrl: "javascript:alert(1)" }); assert.equal(invalid.value, null); assert.ok(invalid.errors.imageUrl); });
test("role changes require a real change and explicit confirmation", () => { assert.match(validateRoleChange("user", "admin", false) ?? "", /Confirm/); assert.match(validateRoleChange("admin", "admin", true) ?? "", /already/); assert.equal(validateRoleChange("user", "admin", true), null); });
test("duration helper formats hours and minutes", () => { assert.equal(formatDuration("2026-01-01T09:00:00Z", "2026-01-01T12:30:00Z"), "3 h 30 min"); assert.equal(formatDuration("2026-01-01T09:00:00Z", "2026-01-01T09:45:00Z"), "45 min"); });
test("audit formatter produces readable summaries without raw JSON", () => { assert.equal(auditSummary("instrument_status_changed", { name: "PPMS", status: "maintenance" }), "Instrument Status Changed · PPMS · Status: maintenance"); });
test("CSV cells escape syntax and neutralize spreadsheet formulas", () => { assert.equal(sanitizeCsvCell("=2+2"), "'=2+2"); assert.equal(sanitizeCsvCell("  @SUM(A1)"), "'  @SUM(A1)"); assert.equal(escapeCsv('sample, "quoted"\nline'), '"sample, ""quoted""\nline"'); assert.equal(escapeCsv("-1+2"), "'-1+2"); });
test("laboratory timezone conversion is independent of server locale", () => { assert.equal(labDateTimeToIso("2026-08-26", "09:00", "Asia/Shanghai"), "2026-08-26T01:00:00Z"); const bounds = labDayBounds(new Date("2026-08-25T20:00:00Z"), "Asia/Shanghai"); assert.deepEqual(bounds, { start: "2026-08-25T16:00:00.000Z", end: "2026-08-26T16:00:00.000Z" }); });
test("exclusion violations map to the public booking conflict code", () => { const result = mapBookingError({ code: "23P01" }); assert.equal(result.success, false); if (!result.success) assert.equal(result.code, "BOOKING_CONFLICT"); });
test("operational migration protects final admin and removes hard deletes", async () => { const sql = await readFile(new URL("../supabase/migrations/202608250005_operational_safety.sql", import.meta.url), "utf8"); assert.match(sql, /LAST_ADMIN/); assert.match(sql, /revoke delete on table public\.instruments, public\.bookings from authenticated/i); assert.match(sql, /Historical bookings are immutable/); });
test("audit migration is trigger-written and admin-readable only", async () => { const sql = await readFile(new URL("../supabase/migrations/202608250006_audit_and_admin_indexes.sql", import.meta.url), "utf8"); assert.match(sql, /revoke all on table public\.audit_logs from anon, authenticated/i); assert.match(sql, /audit_logs_select_admin/); assert.match(sql, /admin_booking_cancelled/); });
test("service-role grants are minimal and keep audit logs read-only", async () => { const sql = await readFile(new URL("../supabase/migrations/202608250007_service_role_table_grants.sql", import.meta.url), "utf8"); assert.match(sql, /grant select, update on table public\.profiles to service_role/i); assert.match(sql, /grant select, insert, update, delete on table public\.instruments to service_role/i); assert.match(sql, /grant select, insert, update, delete on table public\.bookings to service_role/i); assert.match(sql, /grant select on table public\.audit_logs to service_role/i); assert.doesNotMatch(sql, /grant[^;]*(?:insert|update|delete)[^;]*public\.audit_logs[^;]*to service_role/i); });
