"use client";
import { useEffect, useRef, useState, useTransition } from "react";
import { cancelBooking, createBooking, updateBooking } from "@/lib/bookings/mutations";
import { validateBookingInput } from "@/lib/bookings/validation";
import { validateBookingRules } from "@/lib/bookings/rules";
import { datePartsInZone, labDateTimeToIso } from "@/lib/timezone";
import { useI18n } from "@/lib/i18n/client";
import type { FieldErrors } from "@/types/action-result";
import type { BookingInput, CalendarBooking } from "@/types/booking";
import type { Instrument } from "@/types/instrument";

export type BookingDraft = { start: Date; end: Date };
type Props = { instrument: Instrument; draft: BookingDraft; booking?: CalendarBooking; labTimezone?: string; onClose: () => void; onSaved: (message: string) => void; onAvailabilityChanged?: () => void };

function readableDuration(minutes: number, locale: "zh" | "en") { if (minutes % 1440 === 0) return locale === "zh" ? `${minutes / 1440} 天` : `${minutes / 1440} day${minutes === 1440 ? "" : "s"}`; if (minutes % 60 === 0) return locale === "zh" ? `${minutes / 60} 小时` : `${minutes / 60} hour${minutes === 60 ? "" : "s"}`; return locale === "zh" ? `${minutes} 分钟` : `${minutes} minutes`; }
function initialFields(draft: BookingDraft, zone: string, booking?: CalendarBooking) { const start = datePartsInZone(booking?.start_time ?? draft.start, zone); const end = datePartsInZone(booking?.end_time ?? draft.end, zone); return { startDate: start.date, startTime: start.time, endDate: end.date, endTime: end.time, sampleName: booking?.sample_name ?? "", sampleCount: String(booking?.sample_count ?? 1), purpose: booking?.purpose ?? "", notes: booking?.notes ?? "" }; }

export default function BookingForm({ instrument, draft, booking, labTimezone = process.env.NEXT_PUBLIC_LAB_TIMEZONE ?? "UTC", onClose, onSaved, onAvailabilityChanged }: Props) {
  const { locale, t, errorMessage } = useI18n();
  const [fields, setFields] = useState(() => initialFields(draft, labTimezone, booking));
  const [errors, setErrors] = useState<FieldErrors>({}); const [message, setMessage] = useState(""); const [pending, startTransition] = useTransition(); const titleRef = useRef<HTMLHeadingElement>(null);
  useEffect(() => { titleRef.current?.focus(); const close = (event: KeyboardEvent) => { if (event.key === "Escape" && !pending) onClose(); }; window.addEventListener("keydown", close); return () => window.removeEventListener("keydown", close); }, [onClose, pending]);
  const set = (key: keyof typeof fields, value: string) => setFields(current => ({ ...current, [key]: value }));
  const payload = (): BookingInput => ({ startTime: labDateTimeToIso(fields.startDate, fields.startTime, labTimezone), endTime: labDateTimeToIso(fields.endDate, fields.endTime, labTimezone), sampleName: fields.sampleName, sampleCount: Number(fields.sampleCount), purpose: fields.purpose, notes: fields.notes });
  function submit(event: React.FormEvent) { event.preventDefault(); setMessage(""); let input: BookingInput; try { input = payload(); } catch { setErrors({ startTime: t("booking.validDateTime"), endTime: t("booking.validDateTime") }); return; } const checked = validateBookingInput(input); const combined = { ...checked.fieldErrors, ...validateBookingRules(input.startTime, input.endTime, instrument, labTimezone) }; if (!checked.value || Object.keys(combined).length) { setErrors(combined); return; } setErrors({}); startTransition(async () => { const result = booking ? await updateBooking(booking.id, input) : await createBooking(instrument.id, input); if (result.success) onSaved(t(booking ? "booking.updatedSuccess" : "booking.createdSuccess")); else { setMessage(errorMessage(result.code, result.message)); setErrors(result.fieldErrors ?? {}); if (result.code === "BOOKING_CONFLICT") onAvailabilityChanged?.(); } }); }
  function cancel() { if (!booking || !window.confirm(t("booking.cancelPrompt"))) return; startTransition(async () => { const result = await cancelBooking(booking.id); if (result.success) onSaved(t("bookings.cancelledSuccess")); else setMessage(errorMessage(result.code, result.message)); }); }
  const fieldError = (value?: string) => value ? t("error.VALIDATION_ERROR") : undefined;

  return <div className="fixed inset-0 z-50 flex items-end justify-center bg-slate-950/50 sm:items-center sm:p-6" onMouseDown={event => { if (event.target === event.currentTarget && !pending) onClose(); }}><section role="dialog" aria-modal="true" aria-labelledby="booking-dialog-title" className="max-h-[95vh] w-full overflow-y-auto rounded-t-2xl bg-white p-5 shadow-2xl sm:max-w-2xl sm:rounded-2xl sm:p-7">
    <div className="flex justify-between gap-4"><div><p className="eyebrow">{t(booking ? "booking.manage" : "booking.newEyebrow")}</p><h2 ref={titleRef} tabIndex={-1} id="booking-dialog-title" className="mt-1 text-2xl font-bold outline-none">{t(booking ? "booking.edit" : "booking.new")}</h2><p className="mt-1 text-sm text-slate-500">{t("booking.timezone")} {labTimezone}</p></div><button type="button" aria-label={t("booking.closeLabel")} disabled={pending} onClick={onClose} className="grid size-9 place-items-center rounded-full bg-slate-100 text-xl">×</button></div>
    <div className="mt-5 grid gap-2 rounded-xl bg-teal-50 p-4 text-sm sm:grid-cols-3"><p><strong>{t("booking.interval")}：</strong> {readableDuration(instrument.booking_slot_minutes, locale)}</p><p><strong>{t("booking.minimum")}：</strong> {readableDuration(instrument.min_booking_minutes, locale)}</p><p><strong>{t("booking.maximum")}：</strong> {instrument.max_booking_minutes ? readableDuration(instrument.max_booking_minutes, locale) : t("booking.none")}</p></div>
    <form onSubmit={submit} noValidate className="mt-5 space-y-4">
      <label className="block text-sm font-bold">{t("booking.instrument")}<input disabled value={instrument.name} className="mt-2 w-full rounded-lg border border-slate-200 bg-slate-50 p-3 font-normal" /></label>
      <div className="grid gap-3 sm:grid-cols-2"><DateTimeFields prefix={t("booking.start")} dateLabel={t("booking.date")} timeLabel={t("booking.time")} date={fields.startDate} time={fields.startTime} step={instrument.booking_slot_minutes * 60} error={fieldError(errors.startTime)} onDate={value => set("startDate", value)} onTime={value => set("startTime", value)} /><DateTimeFields prefix={t("booking.end")} dateLabel={t("booking.date")} timeLabel={t("booking.time")} date={fields.endDate} time={fields.endTime} step={instrument.booking_slot_minutes * 60} error={fieldError(errors.endTime)} onDate={value => set("endDate", value)} onTime={value => set("endTime", value)} /></div>
      <div className="grid gap-3 sm:grid-cols-[1fr_12rem]"><Field label={t("booking.sample")} id="booking-sample" error={fieldError(errors.sampleName)}><input id="booking-sample" required maxLength={120} value={fields.sampleName} onChange={e => set("sampleName", e.target.value)} className="mt-2 w-full rounded-lg border border-slate-200 p-3 font-normal" /></Field><Field label={t("booking.sampleCount")} id="booking-sample-count" error={fieldError(errors.sampleCount)}><input id="booking-sample-count" required type="number" min="1" max="1000000" step="1" inputMode="numeric" value={fields.sampleCount} onChange={e => set("sampleCount", e.target.value)} className="mt-2 w-full rounded-lg border border-slate-200 p-3 font-normal" /></Field></div>
      <Field label={t("booking.purpose")} id="booking-purpose" error={fieldError(errors.purpose)}><textarea id="booking-purpose" required maxLength={1000} rows={3} value={fields.purpose} onChange={e => set("purpose", e.target.value)} className="mt-2 w-full rounded-lg border border-slate-200 p-3 font-normal" /></Field>
      <Field label={t("booking.notes")} id="booking-notes" error={fieldError(errors.notes)}><textarea id="booking-notes" maxLength={4000} rows={2} value={fields.notes} onChange={e => set("notes", e.target.value)} className="mt-2 w-full rounded-lg border border-slate-200 p-3 font-normal" /></Field>
      {message && <p role="alert" className="rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700">{message}</p>}
      <div className="flex flex-col-reverse justify-between gap-3 pt-2 sm:flex-row"><div>{booking && <button disabled={pending} type="button" onClick={cancel} className="rounded-xl px-4 py-3 font-bold text-red-700">{t("booking.cancel")}</button>}</div><div className="flex gap-3"><button disabled={pending} type="button" onClick={onClose} className="btn-secondary">{t("common.close")}</button><button disabled={pending} className="btn-primary disabled:opacity-60">{pending ? t("common.saving") : t(booking ? "booking.save" : "booking.confirm")}</button></div></div>
    </form>
  </section></div>;
}

function DateTimeFields({ prefix, dateLabel, timeLabel, date, time, step, error, onDate, onTime }: { prefix: string; dateLabel: string; timeLabel: string; date: string; time: string; step: number; error?: string; onDate: (value: string) => void; onTime: (value: string) => void }) { return <fieldset><legend className="text-sm font-bold">{prefix}</legend><div className="mt-2 grid grid-cols-[1fr_8rem] gap-2"><input aria-label={`${prefix} ${dateLabel}`} type="date" required value={date} onChange={e => onDate(e.target.value)} className="w-full rounded-lg border border-slate-200 p-3" /><input aria-label={`${prefix} ${timeLabel}`} type="time" required step={step} value={time} onChange={e => onTime(e.target.value)} className="w-full rounded-lg border border-slate-200 p-3" /></div>{error && <span className="mt-1 block text-xs font-semibold text-red-700">{error}</span>}</fieldset>; }
function Field({ label, id, error, children }: { label: string; id: string; error?: string; children: React.ReactNode }) { return <label className="block text-sm font-bold" htmlFor={id}>{label}{children}{error && <span className="mt-1 block text-xs font-semibold text-red-700">{error}</span>}</label>; }
