"use client";
import { useCallback, useRef, useState } from "react";
import FullCalendar from "@fullcalendar/react";
import dayGridPlugin from "@fullcalendar/daygrid";
import timeGridPlugin from "@fullcalendar/timegrid";
import interactionPlugin from "@fullcalendar/interaction";
import luxonPlugin from "@fullcalendar/luxon3";
import type { DateClickArg } from "@fullcalendar/interaction";
import type { DateSelectArg, EventClickArg, EventInput, EventSourceFuncArg } from "@fullcalendar/core";
import { useRouter } from "next/navigation";
import { loadAvailability } from "@/lib/bookings/availability";
import BookingForm, { type BookingDraft } from "./BookingForm";
import type { CalendarBooking } from "@/types/booking";
import type { Instrument } from "@/types/instrument";

function nextHour() { const start = new Date(); start.setMinutes(0, 0, 0); start.setHours(start.getHours() + 1); return { start, end: new Date(start.getTime() + 60 * 60 * 1000) }; }

export default function BookingCalendar({ instrument, labTimezone }: { instrument: Instrument; labTimezone: string }) {
  const calendarRef = useRef<FullCalendar>(null); const router = useRouter(); const [draft, setDraft] = useState<BookingDraft | null>(null); const [editing, setEditing] = useState<CalendarBooking>(); const [occupied, setOccupied] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState(""); const [calendarLoading, setCalendarLoading] = useState(true); const bookable = instrument.status === "available";
  const events = useCallback((info: EventSourceFuncArg, successCallback: (events: EventInput[]) => void, failureCallback: (error: Error) => void) => { setError(""); loadAvailability(instrument.id, info.start, info.end).then(result => { if (result.error) { setError(result.error); failureCallback(new Error(result.error)); } else successCallback(result.events); }).catch(() => { const message = "Calendar availability could not be loaded."; setError(message); failureCallback(new Error(message)); }); }, [instrument.id]);
  function openRange(start: Date, end: Date) { if (!bookable) return; setSuccess(""); setEditing(undefined); setDraft({ start, end }); }
  function dateClick(info: DateClickArg) { if (info.allDay) { const start = new Date(info.date); start.setHours(9); openRange(start, new Date(start.getTime() + 60 * 60 * 1000)); } else openRange(info.date, new Date(info.date.getTime() + 60 * 60 * 1000)); }
  function eventClick(info: EventClickArg) { if (info.event.extendedProps.kind === "own") { const booking = info.event.extendedProps.booking as CalendarBooking; setEditing(booking); setDraft({ start: new Date(booking.start_time), end: new Date(booking.end_time) }); } else setOccupied(true); }
  function saved(message: string) { setDraft(null); setEditing(undefined); setSuccess(message); calendarRef.current?.getApi().refetchEvents(); router.refresh(); }
  return <section className="card overflow-hidden"><div className="flex flex-col justify-between gap-4 border-b border-slate-100 p-4 sm:flex-row sm:items-center"><div><h2 className="font-bold">Booking calendar</h2><p className="mt-1 text-xs text-slate-500">All times are shown in {labTimezone}. Your bookings are teal; other reservations are marked Occupied.</p></div><button disabled={!bookable} onClick={() => { const range = nextHour(); openRange(range.start, range.end); }} className="btn-primary disabled:cursor-not-allowed disabled:bg-slate-300">{bookable ? "+ New booking" : "Booking unavailable"}</button></div>{error && <div className="m-4 rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700" role="alert">{error} <button onClick={() => calendarRef.current?.getApi().refetchEvents()} className="underline">Try again</button></div>}{success && <div className="m-4 rounded-xl bg-teal-50 p-3 text-sm font-semibold text-teal-800" role="status">{success}</div>}<div className="calendar-wrap relative p-2 sm:p-4">{calendarLoading && <div className="absolute inset-0 z-10 grid place-items-center bg-white/75" role="status"><span className="rounded-full bg-white px-4 py-2 text-sm font-bold text-teal-800 shadow">Loading availability…</span></div>}<FullCalendar ref={calendarRef} plugins={[dayGridPlugin, timeGridPlugin, interactionPlugin, luxonPlugin]} initialView="timeGridWeek" headerToolbar={{ left: "prev,next today", center: "title", right: "dayGridMonth,timeGridWeek,timeGridDay" }} buttonText={{ month: "Month", week: "Week", day: "Day" }} timeZone={labTimezone} nowIndicator selectable={bookable} selectMirror selectOverlap={false} height="auto" contentHeight={650} slotMinTime="06:00:00" slotMaxTime="22:00:00" events={events} loading={setCalendarLoading} select={(info: DateSelectArg) => openRange(info.start, info.end)} dateClick={dateClick} eventClick={eventClick} /></div>{draft && <BookingForm instrument={instrument} draft={draft} booking={editing} labTimezone={labTimezone} onClose={() => { setDraft(null); setEditing(undefined); }} onSaved={saved} onAvailabilityChanged={() => calendarRef.current?.getApi().refetchEvents()} />}{occupied && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-6" onClick={() => setOccupied(false)}><section role="dialog" aria-modal="true" aria-labelledby="occupied-title" className="card max-w-sm p-6" onClick={event => event.stopPropagation()}><p className="eyebrow">Availability</p><h2 id="occupied-title" className="mt-2 text-xl font-bold">This time is occupied</h2><p className="mt-3 text-sm leading-6 text-slate-600">Another laboratory member has reserved this instrument. Booking details remain private.</p><button autoFocus onClick={() => setOccupied(false)} className="btn-primary mt-5 w-full">Choose another time</button></section></div>}</section>;
}
