"use client";
import { useMemo, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import BookingForm from "./BookingForm";
import { cancelBooking } from "@/lib/bookings/mutations";
import { useI18n } from "@/lib/i18n/client";
import type { TranslationKey } from "@/lib/i18n/dictionaries";
import type { BookingWithInstrument, CalendarBooking } from "@/types/booking";

type Tab = "upcoming" | "past" | "cancelled";
const tabKeys: Record<Tab, TranslationKey> = { upcoming: "bookings.upcoming", past: "bookings.past", cancelled: "bookings.cancelled" };
const emptyKeys: Record<Tab, TranslationKey> = { upcoming: "bookings.noUpcoming", past: "bookings.noPast", cancelled: "bookings.noCancelled" };

export default function MyBookings({ bookings }: { bookings: BookingWithInstrument[] }) {
  const { locale, t, errorMessage } = useI18n(); const router = useRouter(); const [tab, setTab] = useState<Tab>("upcoming"); const [editing, setEditing] = useState<BookingWithInstrument>(); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [pending, startTransition] = useTransition(); const now = Date.now(); const dateLocale = locale === "zh" ? "zh-CN" : "en-US";
  const groups = useMemo(() => ({ upcoming: bookings.filter(item => item.status === "confirmed" && new Date(item.end_time).getTime() >= now).sort((a,b) => a.start_time.localeCompare(b.start_time)), past: bookings.filter(item => item.status !== "cancelled" && new Date(item.end_time).getTime() < now).sort((a,b) => b.start_time.localeCompare(a.start_time)), cancelled: bookings.filter(item => item.status === "cancelled").sort((a,b) => b.start_time.localeCompare(a.start_time)) }), [bookings, now]);
  function cancel(item: BookingWithInstrument) { if (!window.confirm(`${item.instrument.name}：${t("bookings.cancelPrompt")}`)) return; setError(""); startTransition(async () => { const result = await cancelBooking(item.id); if (result.success) { setMessage(t("bookings.cancelledSuccess")); router.refresh(); } else setError(errorMessage(result.code, result.message)); }); }
  const visible = groups[tab];
  return <><div className="card p-5 sm:p-7">{message && <p className="mb-5 rounded-xl bg-teal-50 p-3 text-sm font-semibold text-teal-800" role="status">{message}</p>}{error && <p className="mb-5 rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700" role="alert">{error}</p>}<div className="mb-6 flex gap-2 overflow-x-auto border-b border-slate-100 pb-3">{(["upcoming", "past", "cancelled"] as const).map(value => <button key={value} onClick={() => setTab(value)} className={`whitespace-nowrap rounded-lg px-4 py-2 text-sm font-bold ${tab === value ? "bg-teal-50 text-teal-800" : "text-slate-500"}`}>{t(tabKeys[value])} ({groups[value].length})</button>)}</div>{visible.length ? <div className="divide-y divide-slate-100">{visible.map(item => { const eligible = item.status === "confirmed" && new Date(item.start_time).getTime() > now; const statusKey = `bookings.${item.status}` as "bookings.confirmed"|"bookings.cancelled"|"bookings.completed"; return <article key={item.id} className="grid gap-4 py-5 first:pt-0 md:grid-cols-[9rem_1fr_auto] md:items-center"><div><p className="font-black text-teal-800">{new Date(item.start_time).toLocaleDateString(dateLocale, { month: "short", day: "numeric", year: "numeric" })}</p><p className="mt-1 text-xs text-slate-500">{new Date(item.start_time).toLocaleTimeString(dateLocale, { hour: "numeric", minute: "2-digit" })}–{new Date(item.end_time).toLocaleTimeString(dateLocale, { hour: "numeric", minute: "2-digit" })}</p></div><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-bold">{item.instrument.name}</h2><span className={`status ${item.status === "cancelled" ? "status-unavailable" : "status-available"}`}>{t(statusKey)}</span></div><p className="mt-1 text-sm font-semibold text-slate-700">{item.sample_name}</p><p className="mt-1 text-sm text-slate-500">{item.purpose}</p></div>{eligible && <div className="flex gap-2"><button onClick={() => setEditing(item)} className="btn-secondary">{t("common.edit")}</button><button disabled={pending} onClick={() => cancel(item)} className="rounded-xl px-3 py-2 text-sm font-bold text-red-700 hover:bg-red-50 disabled:opacity-50">{t("bookings.cancelAction")}</button></div>}</article>; })}</div> : <div className="py-12 text-center"><h2 className="text-lg font-bold">{t(emptyKeys[tab])}</h2><p className="mt-2 text-sm text-slate-500">{t(tab === "upcoming" ? "bookings.emptyUpcoming" : "bookings.emptyOther")}</p></div>}</div>{editing && <BookingForm instrument={editing.instrument} draft={{ start: new Date(editing.start_time), end: new Date(editing.end_time) }} booking={editing as CalendarBooking} onClose={() => setEditing(undefined)} onSaved={() => { setEditing(undefined); setMessage(t("booking.save")); router.refresh(); }} />}</>;
}
