import PageIntro from "@/components/PageIntro";
import Pagination from "@/components/admin/Pagination";
import { getAuditFilterOptions, getAuditLogs, type AuditFilters } from "@/lib/admin/audit";
import { auditSummary } from "@/lib/admin/format";
import { auditActionLabels, formatAdminDateTime } from "@/lib/admin/labels";
import type { Json } from "@/types/database";
const actions = ["instrument_created", "instrument_updated", "instrument_status_changed", "instrument_archived", "booking_created", "booking_updated", "booking_cancelled", "admin_booking_cancelled", "user_role_changed"];
export default async function AdminAuditPage({ searchParams }: { searchParams: Promise<AuditFilters> }) { const filters = await searchParams; const [result, options] = await Promise.all([getAuditLogs(filters), getAuditFilterOptions()]); return <><PageIntro eyebrow="管理后台" title="审计日志" description="由受保护的数据库触发器生成、仅可追加的系统操作记录。" /><form method="get" className="card mb-5 grid gap-3 p-4 md:grid-cols-4"><label className="text-sm font-bold">操作<select name="action" defaultValue={filters.action ?? ""} className="mt-2 w-full rounded-xl border border-slate-200 p-3 font-normal"><option value="">全部操作</option>{actions.map(action => <option key={action} value={action}>{auditActionLabels[action] ?? action}</option>)}</select></label><label className="text-sm font-bold">操作人<select name="actor" defaultValue={filters.actor ?? ""} className="mt-2 w-full rounded-xl border border-slate-200 p-3 font-normal"><option value="">全部操作人</option>{options.actors.map(actor => <option key={actor.id} value={actor.id}>{actor.full_name} ({actor.email})</option>)}</select></label><label className="text-sm font-bold">开始日期<input name="from" type="date" defaultValue={filters.from} className="mt-2 w-full rounded-xl border border-slate-200 p-3 font-normal" /></label><label className="text-sm font-bold">结束日期<input name="to" type="date" defaultValue={filters.to} className="mt-2 w-full rounded-xl border border-slate-200 p-3 font-normal" /></label><button className="btn-primary md:col-start-4">筛选</button></form>{!result.data ? <div className="card p-6 text-red-700" role="alert">审计记录加载失败，请稍后重试。</div> : <div className="card p-4 sm:p-6">{result.data.items.length ? <div className="divide-y divide-slate-100">{result.data.items.map(log => <article key={log.id} className="grid gap-3 py-5 md:grid-cols-[11rem_13rem_1fr]"><time className="text-sm text-slate-500" dateTime={log.created_at}>{formatAdminDateTime(log.created_at)}</time><div><p className="font-bold">{log.actor?.full_name ?? "系统"}</p><p className="truncate text-xs text-slate-500">{log.actor?.email ?? "无用户操作人"}</p></div><div><p className="font-semibold">{auditSummary(log.action, log.metadata)}</p><p className="mt-1 text-xs tracking-wide text-slate-500">{log.entity_type} · {log.entity_id ?? "无"}</p><details className="mt-2"><summary className="cursor-pointer text-sm font-bold text-teal-700">详细信息</summary><dl className="mt-2 grid gap-1 text-sm">{metadataEntries(log.metadata).map(([key, value]) => <div key={key} className="grid grid-cols-[10rem_1fr] gap-2"><dt className="font-semibold text-slate-500">{key.replaceAll("_", " ")}</dt><dd className="break-words">{value}</dd></div>)}</dl></details></div></article>)}</div> : <div className="py-10 text-center"><h2 className="font-bold">没有符合筛选条件的审计记录</h2></div>}<Pagination page={result.data.page} pageCount={result.data.pageCount} total={result.data.total} params={{ page: filters.page, action: filters.action, actor: filters.actor, from: filters.from, to: filters.to }} /></div>}</>; }
function metadataEntries(metadata: Json): [string, string][] { if (!metadata || typeof metadata !== "object" || Array.isArray(metadata)) return []; return Object.entries(metadata).filter((entry): entry is [string, Json] => entry[1] !== undefined).map(([key, value]) => [key, value === null ? "—" : typeof value === "object" ? "结构化数据" : String(value)]); }
