import ExcelJS from "exceljs";
import { DateTime } from "luxon";
import type { AdminBooking } from "@/types/booking";
export const LEDGER_HEADERS = ["序号", "使用编号", "仪器名称", "资产编号", "使用者", "所属单位", "使用开始时间", "使用结束时间", "使用时长（小时）", "统计时长（小时）", "样品数", "付费人", "付费人机构", "扣费状态", "是否签订合同", "合同金额（元）", "用户评价表", "用户调研"] as const;
const billing = { pending: "待扣费", charged: "已扣费", exempt: "免收费", not_applicable: "不适用" } as const; const contract = { signed: "是", not_signed: "否", not_required: "无需填写" } as const; const evaluation = { submitted: "已提交", not_submitted: "未提交", not_required: "无需填写" } as const; const survey = { completed: "已完成", not_completed: "未完成", not_required: "无需填写" } as const;
export function durationHours(start: string, end: string) { return Math.round(((new Date(end).getTime() - new Date(start).getTime()) / 3600000) * 1000) / 1000; }
export function usageNumber(item: Pick<AdminBooking, "id" | "start_time" | "instrument">, zone: string) { const date = DateTime.fromISO(item.start_time).setZone(zone).toFormat("yyyyLLdd"); const code = item.instrument.name.replace(/[^A-Za-z0-9]/g, "").slice(0, 4).toUpperCase() || "INST"; return `${date}-${code}-${item.id.replaceAll("-", "").slice(0, 6).toUpperCase()}`; }
export function ledgerRow(item: AdminBooking, index: number, zone: string) { const hours = durationHours(item.start_time, item.end_time); const detail = item.ledger; return [index, usageNumber(item, zone), item.instrument.name, item.instrument.asset_number ?? "", item.user.full_name, item.user.group_name ?? "", DateTime.fromISO(item.start_time).setZone(zone).toFormat("yyyy-LL-dd HH:mm"), DateTime.fromISO(item.end_time).setZone(zone).toFormat("yyyy-LL-dd HH:mm"), hours, detail?.statistical_hours ?? hours, item.sample_count ?? detail?.sample_count ?? 1, detail?.payer_name ?? "", detail?.payer_organization ?? "", billing[detail?.billing_status ?? "pending"], contract[detail?.contract_status ?? "not_required"], detail?.contract_amount ?? null, evaluation[detail?.evaluation_status ?? "not_required"], survey[detail?.survey_status ?? "not_required"]]; }
export async function buildLedgerWorkbook(items: AdminBooking[], zone: string, years: number[]) { const workbook = new ExcelJS.Workbook(); workbook.creator = "SUSTech Low-Dimensional Magnetic Materials Laboratory Booking System"; for (const year of years) { const sheet = workbook.addWorksheet(`${year}年度`, { views: [{ state: "frozen", ySplit: 2 }] }); sheet.addRow([...LEDGER_HEADERS]); sheet.addRow(["系统按所选实验室时区导出；统计时长默认等于使用时长，可由管理员覆盖。", ...Array(13).fill(""), "校外用户按学校要求填写合同、评价与调研信息。", "", "", ""]); sheet.mergeCells("A2:N2"); sheet.mergeCells("O2:R2"); items.filter(item => DateTime.fromISO(item.start_time).setZone(zone).year === year).forEach((item, index) => sheet.addRow(ledgerRow(item, index + 1, zone))); sheet.getRow(1).font = { bold: true, color: { argb: "FFFFFFFF" } }; sheet.getRow(1).fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF0F766E" } }; sheet.getRow(2).alignment = { wrapText: true, vertical: "middle" }; [15,16,17,18].forEach(column => { sheet.getCell(1, column).font = { bold: true, color: { argb: "FFFF0000" } }; }); sheet.columns.forEach((column, index) => { column.width = [7,22,22,16,14,20,20,20,14,14,10,14,20,14,16,16,16,14][index]; }); sheet.getColumn(9).numFmt = "0.000"; sheet.getColumn(10).numFmt = "0.000"; sheet.getColumn(16).numFmt = "#,##0.00"; sheet.autoFilter = "A1:R1"; } return workbook.xlsx.writeBuffer(); }
