"use server";
import { revalidatePath } from "next/cache";
import { getAdminContext } from "./auth";
import { mapAdminError } from "./errors";
import { validateAdminBooking, validateInstrument, validateRoleChange } from "./validation";
import type { AdminResult, InstrumentAdminInput } from "@/types/admin";
import type { Booking, BookingInput } from "@/types/booking";
import type { Instrument, InstrumentStatus } from "@/types/instrument";
import type { Profile, UserRole } from "@/types/database";

function refreshAdmin() { revalidatePath("/admin"); revalidatePath("/admin/instruments"); revalidatePath("/admin/bookings"); revalidatePath("/admin/users"); revalidatePath("/admin/audit"); }
async function futureBookingCount(context: NonNullable<Awaited<ReturnType<typeof getAdminContext>>>, instrumentId: string) { const { count, error } = await context.supabase.from("bookings").select("id", { count: "exact", head: true }).eq("instrument_id", instrumentId).eq("status", "confirmed").gt("start_time", new Date().toISOString()); return { count: count ?? 0, error }; }

export async function createInstrument(input: InstrumentAdminInput): Promise<AdminResult<Instrument>> { const context = await getAdminContext(); if (!context) return { success: false, code: "FORBIDDEN", message: "Administrator permission is required." }; const checked = validateInstrument(input); if (!checked.value) return { success: false, code: "VALIDATION_ERROR", message: "Check the highlighted fields.", fieldErrors: checked.errors }; const { data, error } = await context.supabase.from("instruments").insert(checked.value).select().single(); if (error) return mapAdminError(error); refreshAdmin(); revalidatePath("/instruments"); return { success: true, data, message: "Instrument created." }; }

export async function updateInstrument(id: string, input: InstrumentAdminInput): Promise<AdminResult<Instrument>> { const context = await getAdminContext(); if (!context) return { success: false, code: "FORBIDDEN", message: "Administrator permission is required." }; const checked = validateInstrument(input); if (!checked.value) return { success: false, code: "VALIDATION_ERROR", message: "Check the highlighted fields.", fieldErrors: checked.errors }; const existing = await context.supabase.from("instruments").select("*").eq("id", id).maybeSingle(); if (existing.error) return mapAdminError(existing.error); if (!existing.data) return { success: false, code: "NOT_FOUND", message: "Instrument not found." }; if (checked.value.status !== "available" && checked.value.status !== existing.data.status) { const future = await futureBookingCount(context, id); if (future.error) return mapAdminError(future.error); if (future.count > 0) return { success: false, code: "HAS_FUTURE_BOOKINGS", message: `This instrument has ${future.count} future reservations. Confirm the status change separately.`, futureBookingCount: future.count }; } const { data, error } = await context.supabase.from("instruments").update(checked.value).eq("id", id).select().single(); if (error) return mapAdminError(error); refreshAdmin(); revalidatePath("/instruments"); revalidatePath(`/instruments/${id}`); return { success: true, data, message: "Instrument updated." }; }

export async function changeInstrumentStatus(id: string, status: InstrumentStatus, confirmed: boolean): Promise<AdminResult<Instrument>> { const context = await getAdminContext(); if (!context) return { success: false, code: "FORBIDDEN", message: "Administrator permission is required." }; if (!(["available", "maintenance", "unavailable"] as string[]).includes(status)) return { success: false, code: "VALIDATION_ERROR", message: "Choose a valid instrument status." }; const existing = await context.supabase.from("instruments").select("*").eq("id", id).maybeSingle(); if (existing.error) return mapAdminError(existing.error); if (!existing.data) return { success: false, code: "NOT_FOUND", message: "Instrument not found." }; const future = await futureBookingCount(context, id); if (future.error) return mapAdminError(future.error); if (status !== "available" && future.count > 0 && !confirmed) return { success: false, code: "HAS_FUTURE_BOOKINGS", message: `This instrument has ${future.count} future reservations. They will remain confirmed.`, futureBookingCount: future.count }; const { data, error } = await context.supabase.from("instruments").update({ status }).eq("id", id).select().single(); if (error) return mapAdminError(error); refreshAdmin(); revalidatePath("/instruments"); revalidatePath(`/instruments/${id}`); return { success: true, data, message: `Instrument marked ${status}. Existing bookings were not changed.` }; }

export async function archiveInstrument(id: string, confirmed: boolean): Promise<AdminResult<Instrument>> { const context = await getAdminContext(); if (!context) return { success: false, code: "FORBIDDEN", message: "Administrator permission is required." }; const future = await futureBookingCount(context, id); if (future.error) return mapAdminError(future.error); if (!confirmed) return { success: false, code: future.count ? "HAS_FUTURE_BOOKINGS" : "VALIDATION_ERROR", message: future.count ? `This instrument has ${future.count} future reservations. Archiving will not cancel them.` : "Confirm instrument archival before continuing.", futureBookingCount: future.count }; const { data, error } = await context.supabase.from("instruments").update({ archived_at: new Date().toISOString(), status: "unavailable" }).eq("id", id).is("archived_at", null).select().single(); if (error) return mapAdminError(error); refreshAdmin(); revalidatePath("/instruments"); return { success: true, data, message: "Instrument archived. Booking history was preserved." }; }

export async function changeUserRole(userId: string, role: UserRole, confirmed: boolean): Promise<AdminResult<Profile>> { const context = await getAdminContext(); if (!context) return { success: false, code: "FORBIDDEN", message: "Administrator permission is required." }; const existing = await context.supabase.from("profiles").select("*").eq("id", userId).maybeSingle(); if (existing.error) return mapAdminError(existing.error); if (!existing.data) return { success: false, code: "NOT_FOUND", message: "User not found." }; const validation = validateRoleChange(existing.data.role, role, confirmed); if (validation) return { success: false, code: "VALIDATION_ERROR", message: validation }; const { data, error } = await context.supabase.from("profiles").update({ role }).eq("id", userId).select().single(); if (error) return mapAdminError(error); refreshAdmin(); return { success: true, data, message: `${data.full_name} is now ${role === "admin" ? "an administrator" : "a standard user"}.` }; }

export async function adminCancelBooking(bookingId: string, reason: string, confirmed: boolean): Promise<AdminResult<Booking>> { const context = await getAdminContext(); if (!context) return { success: false, code: "FORBIDDEN", message: "Administrator permission is required." }; if (!confirmed) return { success: false, code: "VALIDATION_ERROR", message: "Confirm administrative cancellation." }; const cleanReason = reason.trim(); if (cleanReason.length < 3 || cleanReason.length > 1000) return { success: false, code: "VALIDATION_ERROR", message: "Provide a cancellation reason of 3–1,000 characters.", fieldErrors: { reason: "A clear reason is required." } }; const existing = await context.supabase.from("bookings").select("*").eq("id", bookingId).maybeSingle(); if (existing.error) return mapAdminError(existing.error); if (!existing.data) return { success: false, code: "NOT_FOUND", message: "Booking not found." }; if (existing.data.status === "cancelled") return { success: false, code: "CONFLICT", message: "This booking is already cancelled." }; const { data, error } = await context.supabase.from("bookings").update({ status: "cancelled", cancellation_reason: cleanReason }).eq("id", bookingId).select().single(); if (error) return mapAdminError(error); refreshAdmin(); revalidatePath("/bookings"); revalidatePath(`/instruments/${existing.data.instrument_id}`); return { success: true, data, message: "Booking cancelled. The history record was preserved." }; }

export async function updateAdminBooking(bookingId: string, input: BookingInput): Promise<AdminResult<Booking>> { const context = await getAdminContext(); if (!context) return { success: false, code: "FORBIDDEN", message: "Administrator permission is required." }; const checked = validateAdminBooking(input); if (!checked.value) return { success: false, code: "VALIDATION_ERROR", message: "Check the booking fields.", fieldErrors: checked.fieldErrors }; const existing = await context.supabase.from("bookings").select("*").eq("id", bookingId).maybeSingle(); if (existing.error) return mapAdminError(existing.error); if (!existing.data) return { success: false, code: "NOT_FOUND", message: "Booking not found." }; if (existing.data.status !== "confirmed" || new Date(existing.data.start_time) <= new Date()) return { success: false, code: "CONFLICT", message: "Only future confirmed bookings can be edited." }; const value = checked.value; const { data, error } = await context.supabase.from("bookings").update({ start_time: value.startTime, end_time: value.endTime, sample_name: value.sampleName, sample_count: value.sampleCount, purpose: value.purpose, notes: value.notes }).eq("id", bookingId).select().single(); if (error) return mapAdminError(error); refreshAdmin(); revalidatePath("/bookings"); revalidatePath(`/instruments/${existing.data.instrument_id}`); return { success: true, data, message: "Booking updated." }; }
