import type { Locale } from "./config";

const en = {
  "brand.short":"SUSTech LDMM Lab", "brand.full":"SUSTech Low-Dimensional Magnetic Materials Laboratory Booking System", "nav.dashboard":"Dashboard", "nav.instruments":"Instruments", "nav.bookings":"My bookings", "nav.admin":"Admin", "nav.profile":"Profile", "nav.logout":"Logout",
  "auth.signin":"Sign in", "auth.signup":"Create account", "auth.name":"Full name", "auth.email":"University email", "auth.password":"Password", "auth.wait":"Please wait…", "login.access":"Member access", "login.welcome":"Welcome to the laboratory booking system", "login.help":"Sign in with your laboratory account or register as a new member.",
  "calendar.title":"Booking calendar", "calendar.new":"New booking", "calendar.unavailable":"Booking unavailable", "calendar.occupied":"Reserved by", "calendar.private":"Other booking details remain private.", "calendar.retry":"Try again", "booking.interval":"Booking interval", "booking.minimum":"Minimum booking", "booking.maximum":"Maximum booking", "booking.none":"No maximum", "booking.edit":"Edit booking", "booking.new":"Reserve instrument", "booking.confirm":"Confirm booking", "booking.save":"Save changes", "booking.cancel":"Cancel booking",
  "common.close":"Close", "common.cancel":"Cancel", "common.edit":"Edit", "common.saving":"Saving…", "common.working":"Working…", "common.loading":"Loading…", "common.keepUnchanged":"Keep unchanged", "instrument.available":"Available", "instrument.maintenance":"Maintenance", "instrument.unavailable":"Unavailable", "instrument.archived":"Archived",
  "error.BOOKING_CONFLICT":"This time slot conflicts with an existing booking. Please choose another time.", "error.INSTRUMENT_UNAVAILABLE":"This instrument is currently unavailable for booking.", "error.VALIDATION_ERROR":"Please check the highlighted fields.", "error.FORBIDDEN":"You do not have permission to perform this action.", "error.NOT_FOUND":"The requested record was not found.", "error.LAST_ADMIN":"The final administrator cannot be demoted.", "error.HAS_FUTURE_BOOKINGS":"This instrument has future reservations. Review the warning before continuing.", "error.DATABASE_ERROR":"The operation could not be completed. Please try again.",
  "admin.dashboard":"Laboratory administration", "admin.instruments":"Instrument management", "admin.bookings":"Booking administration", "admin.users":"User management", "admin.audit":"Audit log", "admin.instrument.eyebrow":"Administration", "admin.instrument.description":"Add equipment, coordinate maintenance, review affected reservations, and archive safely without breaking history.",
  "admin.instrument.add":"Add instrument", "admin.instrument.edit":"Edit instrument", "admin.instrument.save":"Save instrument", "admin.instrument.name":"Name", "admin.instrument.assetNumber":"Asset number (optional)", "admin.instrument.location":"Location", "admin.instrument.manager":"Manager", "admin.instrument.descriptionField":"Description", "admin.instrument.imageUrl":"Image URL (optional)", "admin.instrument.initialStatus":"Initial status",
  "admin.instrument.rulesHeading":"Booking rules", "admin.instrument.rulesHelp":"Choose readable time periods; the system stores their canonical minute values.", "admin.instrument.rulesHistory":"New rules apply to new and edited confirmed bookings. Existing history is not rewritten.", "admin.instrument.statusHelp":"Status changes use the explicit controls on the instrument list so affected bookings are always shown first.",
  "admin.instrument.futureNone":"No future confirmed reservations", "admin.instrument.futureOne":"1 future confirmed reservation", "admin.instrument.futureMany":"future confirmed reservations", "admin.instrument.markAvailable":"Mark available", "admin.instrument.markMaintenance":"Mark maintenance", "admin.instrument.markUnavailable":"Mark unavailable", "admin.instrument.archive":"Archive", "admin.instrument.archiveTitle":"Archive instrument?", "admin.instrument.statusTitle":"Change instrument status?", "admin.instrument.archiveConfirm":"Archive instrument", "admin.instrument.statusConfirm":"Change status", "admin.instrument.confirmBase":"Existing bookings will remain visible and will not be cancelled automatically.", "admin.instrument.confirmArchive":"The instrument will disappear from normal discovery.",
  "admin.instrument.emptyTitle":"No instruments", "admin.instrument.emptyDescription":"Add the laboratory’s first instrument to begin scheduling.", "admin.instrument.created":"Instrument created.", "admin.instrument.updated":"Instrument updated.", "admin.instrument.statusChanged":"Instrument status updated. Existing bookings were not changed.", "admin.instrument.archivedSuccess":"Instrument archived. Booking history was preserved.",
  "dashboard.unauthorized":"Administrator access is required for that page.", "dashboard.welcome":"Welcome", "dashboard.description":"Here is your live laboratory schedule.", "dashboard.book":"Book an instrument", "dashboard.available":"Available instruments", "dashboard.next":"Your next session", "dashboard.noneScheduled":"Nothing scheduled", "dashboard.upcoming":"Upcoming bookings", "dashboard.activity":"Your activity", "dashboard.recent":"Recent bookings", "dashboard.viewAll":"View all", "dashboard.empty":"No booking activity yet", "dashboard.emptyHelp":"Your reservations will appear here.",
  "instruments.eyebrow":"Core facilities", "instruments.title":"Find an instrument", "instruments.description":"Review live availability, capabilities, and booking calendars for shared laboratory equipment.", "instruments.loadError":"Instruments are unavailable", "instruments.tryAgain":"Please try again shortly.", "instruments.empty":"No instruments yet", "instruments.emptyHelp":"An administrator needs to add the laboratory’s first instrument.", "instruments.search":"Search instruments, locations, or managers", "instruments.searchLabel":"Search instruments", "instruments.filterLabel":"Filter by status", "instruments.allStatuses":"All statuses", "instruments.noMatch":"No matching instruments", "instruments.noMatchHelp":"Try changing the search or status filter.", "instruments.viewCalendar":"View booking calendar", "instrument.loadError":"Instrument unavailable", "instrument.managedBy":"Managed by", "instrument.bookingDisabled":"New reservations are disabled while this instrument is unavailable.", "instrument.notFoundEyebrow":"Not found", "instrument.notFound":"Instrument not found", "instrument.notFoundHelp":"This instrument may have been removed or the link may be incorrect.", "instrument.browse":"Browse instruments",
  "bookings.eyebrow":"Personal schedule", "bookings.title":"My bookings", "bookings.description":"Review upcoming reservations, manage eligible sessions, or browse past and cancelled bookings.", "bookings.loadError":"Bookings are unavailable", "bookings.upcoming":"Upcoming", "bookings.past":"Past", "bookings.cancelled":"Cancelled", "bookings.confirmed":"Confirmed", "bookings.completed":"Completed", "bookings.noUpcoming":"No upcoming bookings", "bookings.noPast":"No past bookings", "bookings.noCancelled":"No cancelled bookings", "bookings.emptyUpcoming":"Choose an available instrument to schedule your next session.", "bookings.emptyOther":"Bookings will appear here when available.", "bookings.cancelPrompt":"Cancel this booking? The record will remain in your history.", "bookings.cancelAction":"Cancel", "bookings.cancelledSuccess":"Booking cancelled.",
  "booking.manage":"Manage reservation", "booking.newEyebrow":"New reservation", "booking.timezone":"All times are shown in", "booking.instrument":"Instrument", "booking.start":"Start", "booking.end":"End", "booking.date":"date", "booking.time":"time", "booking.sample":"Sample name", "booking.purpose":"Experiment purpose", "booking.notes":"Notes (optional)", "booking.closeLabel":"Close booking form", "booking.cancelPrompt":"Cancel this booking? The record will remain in your history.", "booking.validDateTime":"Choose valid dates and times.", "booking.createdSuccess":"Booking confirmed.", "booking.updatedSuccess":"Booking updated.",
  "calendar.loadError":"Calendar availability could not be loaded.", "calendar.availability":"Availability", "calendar.chooseAnother":"Choose another time", "calendar.timeUnit":"min",
  "duration.15m":"15 minutes", "duration.30m":"30 minutes", "duration.45m":"45 minutes", "duration.1h":"1 hour", "duration.2h":"2 hours", "duration.3h":"3 hours", "duration.4h":"4 hours", "duration.6h":"6 hours", "duration.8h":"8 hours", "duration.halfDay":"Half day (12 hours)", "duration.1d":"1 day", "duration.2d":"2 days", "duration.3d":"3 days", "duration.1w":"1 week", "duration.2w":"2 weeks", "duration.30d":"30 days", "duration.custom":"Custom duration",
} as const;

const zh: Record<keyof typeof en, string> = {
  "brand.short":"南科大低维磁性材料实验室", "brand.full":"南方科技大学-低维磁性材料实验室预约系统", "nav.dashboard":"首页", "nav.instruments":"仪器设备", "nav.bookings":"我的预约", "nav.admin":"管理后台", "nav.profile":"个人资料", "nav.logout":"退出登录",
  "auth.signin":"登录", "auth.signup":"注册账号", "auth.name":"姓名", "auth.email":"学校邮箱", "auth.password":"密码", "auth.wait":"请稍候…", "login.access":"成员入口", "login.welcome":"欢迎使用实验室预约系统", "login.help":"请使用实验室账号登录，或注册成为新成员。",
  "calendar.title":"预约日历", "calendar.new":"新建预约", "calendar.unavailable":"当前不可预约", "calendar.occupied":"预约人", "calendar.private":"其他预约详情受隐私保护。", "calendar.retry":"重试", "booking.interval":"预约间隔", "booking.minimum":"最短预约时长", "booking.maximum":"最长预约时长", "booking.none":"不限", "booking.edit":"编辑预约", "booking.new":"预约仪器", "booking.confirm":"确认预约", "booking.save":"保存修改", "booking.cancel":"取消预约",
  "common.close":"关闭", "common.cancel":"取消", "common.edit":"编辑", "common.saving":"保存中…", "common.working":"处理中…", "common.loading":"加载中…", "common.keepUnchanged":"保持不变", "instrument.available":"可预约", "instrument.maintenance":"维护中", "instrument.unavailable":"不可用", "instrument.archived":"已归档",
  "error.BOOKING_CONFLICT":"该时间段已与现有预约冲突，请选择其他时间。", "error.INSTRUMENT_UNAVAILABLE":"该仪器当前不可预约。", "error.VALIDATION_ERROR":"请检查标出的字段。", "error.FORBIDDEN":"您无权执行此操作。", "error.NOT_FOUND":"未找到所请求的记录。", "error.LAST_ADMIN":"不能移除最后一名管理员。", "error.HAS_FUTURE_BOOKINGS":"该仪器仍有未来预约，请确认提示信息后再继续。", "error.DATABASE_ERROR":"操作未能完成，请稍后重试。",
  "admin.dashboard":"实验室管理", "admin.instruments":"仪器管理", "admin.bookings":"预约管理", "admin.users":"用户管理", "admin.audit":"审计日志", "admin.instrument.eyebrow":"管理后台", "admin.instrument.description":"添加仪器、协调维护安排、查看受影响的预约，并在不破坏历史记录的前提下安全归档。",
  "admin.instrument.add":"添加仪器", "admin.instrument.edit":"编辑仪器", "admin.instrument.save":"保存仪器", "admin.instrument.name":"仪器名称", "admin.instrument.assetNumber":"资产编号（选填）", "admin.instrument.location":"存放位置", "admin.instrument.manager":"负责人", "admin.instrument.descriptionField":"仪器说明", "admin.instrument.imageUrl":"图片网址（选填）", "admin.instrument.initialStatus":"初始状态",
  "admin.instrument.rulesHeading":"预约规则", "admin.instrument.rulesHelp":"请选择易读的时间长度；系统仍会保存对应的标准分钟数。", "admin.instrument.rulesHistory":"新规则仅适用于新建或编辑后的已确认预约，不会改写已有历史记录。", "admin.instrument.statusHelp":"请在仪器列表中单独修改状态，以便先查看受影响的未来预约。",
  "admin.instrument.futureNone":"没有未来的已确认预约", "admin.instrument.futureOne":"1 条未来的已确认预约", "admin.instrument.futureMany":"条未来的已确认预约", "admin.instrument.markAvailable":"设为可预约", "admin.instrument.markMaintenance":"设为维护中", "admin.instrument.markUnavailable":"设为不可用", "admin.instrument.archive":"归档", "admin.instrument.archiveTitle":"归档这台仪器？", "admin.instrument.statusTitle":"修改仪器状态？", "admin.instrument.archiveConfirm":"确认归档", "admin.instrument.statusConfirm":"确认修改状态", "admin.instrument.confirmBase":"现有预约将继续显示，且不会被自动取消。", "admin.instrument.confirmArchive":"归档后，普通用户将无法在仪器列表中找到它。",
  "admin.instrument.emptyTitle":"暂无仪器", "admin.instrument.emptyDescription":"添加实验室的第一台仪器后即可开始安排预约。", "admin.instrument.created":"仪器已创建。", "admin.instrument.updated":"仪器已更新。", "admin.instrument.statusChanged":"仪器状态已更新，现有预约未被修改。", "admin.instrument.archivedSuccess":"仪器已归档，预约历史已保留。",
  "dashboard.unauthorized":"该页面仅限管理员访问。", "dashboard.welcome":"欢迎", "dashboard.description":"这是您当前的实验室预约安排。", "dashboard.book":"预约仪器", "dashboard.available":"可预约仪器", "dashboard.next":"下一次预约", "dashboard.noneScheduled":"暂无安排", "dashboard.upcoming":"即将开始的预约", "dashboard.activity":"预约动态", "dashboard.recent":"最近预约", "dashboard.viewAll":"查看全部", "dashboard.empty":"暂无预约记录", "dashboard.emptyHelp":"您的预约记录将显示在这里。",
  "instruments.eyebrow":"实验室共享设备", "instruments.title":"查找仪器", "instruments.description":"查看实验室共享仪器的实时状态、设备信息和预约日历。", "instruments.loadError":"暂时无法加载仪器", "instruments.tryAgain":"请稍后重试。", "instruments.empty":"暂无仪器", "instruments.emptyHelp":"请联系管理员添加实验室仪器。", "instruments.search":"搜索仪器、位置或负责人", "instruments.searchLabel":"搜索仪器", "instruments.filterLabel":"按状态筛选", "instruments.allStatuses":"全部状态", "instruments.noMatch":"没有符合条件的仪器", "instruments.noMatchHelp":"请尝试修改搜索内容或状态筛选。", "instruments.viewCalendar":"查看预约日历", "instrument.loadError":"暂时无法加载仪器", "instrument.managedBy":"负责人", "instrument.bookingDisabled":"该仪器当前不可预约，暂时无法新建预约。", "instrument.notFoundEyebrow":"未找到", "instrument.notFound":"未找到该仪器", "instrument.notFoundHelp":"该仪器可能已被移除，或当前链接不正确。", "instrument.browse":"浏览仪器",
  "bookings.eyebrow":"个人日程", "bookings.title":"我的预约", "bookings.description":"查看即将开始的预约、管理可修改的预约，或浏览过去及已取消的记录。", "bookings.loadError":"暂时无法加载预约", "bookings.upcoming":"即将开始", "bookings.past":"历史记录", "bookings.cancelled":"已取消", "bookings.confirmed":"已确认", "bookings.completed":"已完成", "bookings.noUpcoming":"暂无即将开始的预约", "bookings.noPast":"暂无历史预约", "bookings.noCancelled":"暂无已取消预约", "bookings.emptyUpcoming":"请选择可用仪器安排下一次实验。", "bookings.emptyOther":"相关预约记录将显示在这里。", "bookings.cancelPrompt":"确定取消这条预约吗？记录仍会保留在历史中。", "bookings.cancelAction":"取消", "bookings.cancelledSuccess":"预约已取消。",
  "booking.manage":"管理预约", "booking.newEyebrow":"新建预约", "booking.timezone":"所有时间均按以下时区显示", "booking.instrument":"仪器", "booking.start":"开始时间", "booking.end":"结束时间", "booking.date":"日期", "booking.time":"时间", "booking.sample":"样品名称", "booking.purpose":"实验目的", "booking.notes":"备注（选填）", "booking.closeLabel":"关闭预约表单", "booking.cancelPrompt":"确定取消这条预约吗？记录仍会保留在历史中。", "booking.validDateTime":"请选择有效的日期和时间。", "booking.createdSuccess":"预约已确认。", "booking.updatedSuccess":"预约已更新。",
  "calendar.loadError":"暂时无法加载预约日历。", "calendar.availability":"预约情况", "calendar.chooseAnother":"选择其他时间", "calendar.timeUnit":"分钟",
  "duration.15m":"15 分钟", "duration.30m":"30 分钟", "duration.45m":"45 分钟", "duration.1h":"1 小时", "duration.2h":"2 小时", "duration.3h":"3 小时", "duration.4h":"4 小时", "duration.6h":"6 小时", "duration.8h":"8 小时", "duration.halfDay":"半天（12 小时）", "duration.1d":"1 天", "duration.2d":"2 天", "duration.3d":"3 天", "duration.1w":"1 周", "duration.2w":"2 周", "duration.30d":"30 天", "duration.custom":"自定义时长",
};

export type TranslationKey = keyof typeof en;
export const dictionaries = { en, zh } satisfies Record<Locale, Record<TranslationKey, string>>;
