"use client";
import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import ConfirmDialog from "./ConfirmDialog";
import { changeUserRole } from "@/lib/admin/mutations";
import { formatAdminDate, roleLabels } from "@/lib/admin/labels";
import type { AdminUser } from "@/types/admin";
import type { UserRole } from "@/types/database";
export default function UserAdmin({ users, currentUserId }: { users: AdminUser[]; currentUserId: string }) { const router = useRouter(); const [target, setTarget] = useState<{ user: AdminUser; role: UserRole }>(); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [pending, startTransition] = useTransition(); return <>{message && <p role="status" className="mb-4 rounded-xl bg-teal-50 p-3 text-sm font-semibold text-teal-800">{message}</p>}{error && <p role="alert" className="mb-4 rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700">{error}</p>}<div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead><tr className="border-b border-slate-200 text-slate-500"><th className="p-3">成员</th><th className="p-3">课题组</th><th className="p-3">角色</th><th className="p-3">创建时间</th><th className="p-3 text-right">操作</th></tr></thead><tbody>{users.map(user => <tr key={user.id} className="border-b border-slate-100"><td className="p-3"><p className="font-bold">{user.full_name}{user.id === currentUserId ? "（当前用户）" : ""}</p><p className="text-slate-500">{user.email}</p></td><td className="p-3">{user.group_name ?? "—"}</td><td className="p-3"><span className="status status-available">{roleLabels[user.role] ?? user.role}</span></td><td className="p-3">{formatAdminDate(user.created_at)}</td><td className="p-3 text-right"><button onClick={() => setTarget({ user, role: user.role === "admin" ? "user" : "admin" })} className="btn-secondary">{user.role === "admin" ? "取消管理员权限" : "设为管理员"}</button></td></tr>)}</tbody></table></div>{target && <ConfirmDialog title={target.role === "admin" ? "设为管理员？" : "取消管理员权限？"} message={target.user.id === currentUserId ? "你正在修改自己的管理员权限。如果还有其他管理员，修改后你将立即无法访问这些页面；如果你是最后一名管理员，数据库会拒绝此操作。" : `${target.user.full_name}将${target.role === "admin" ? "获得仪器、全部预约、用户、导出和审计记录的管理权限" : "失去全部管理员权限"}。`} confirmLabel={target.role === "admin" ? "设为管理员" : "取消管理员权限"} cancelLabel="取消" pendingLabel="处理中……" dangerous={target.role === "user"} pending={pending} onClose={() => setTarget(undefined)} onConfirm={() => startTransition(async () => { const result = await changeUserRole(target.user.id, target.role, true); if (result.success) { setMessage(result.message); setTarget(undefined); router.refresh(); } else setError(result.message); })} />}</>; }
