"use client";
import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import ConfirmDialog from "./ConfirmDialog";
import { changeUserRole } from "@/lib/admin/mutations";
import type { AdminUser } from "@/types/admin";
import type { UserRole } from "@/types/database";
export default function UserAdmin({ users, currentUserId }: { users: AdminUser[]; currentUserId: string }) { const router = useRouter(); const [target, setTarget] = useState<{ user: AdminUser; role: UserRole }>(); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [pending, startTransition] = useTransition(); return <>{message && <p role="status" className="mb-4 rounded-xl bg-teal-50 p-3 text-sm font-semibold text-teal-800">{message}</p>}{error && <p role="alert" className="mb-4 rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700">{error}</p>}<div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead><tr className="border-b border-slate-200 text-slate-500"><th className="p-3">Member</th><th className="p-3">Group</th><th className="p-3">Role</th><th className="p-3">Created</th><th className="p-3 text-right">Action</th></tr></thead><tbody>{users.map(user => <tr key={user.id} className="border-b border-slate-100"><td className="p-3"><p className="font-bold">{user.full_name}{user.id === currentUserId ? " (you)" : ""}</p><p className="text-slate-500">{user.email}</p></td><td className="p-3">{user.group_name ?? "—"}</td><td className="p-3"><span className="status status-available">{user.role}</span></td><td className="p-3">{new Date(user.created_at).toLocaleDateString()}</td><td className="p-3 text-right"><button onClick={() => setTarget({ user, role: user.role === "admin" ? "user" : "admin" })} className="btn-secondary">{user.role === "admin" ? "Demote" : "Promote"}</button></td></tr>)}</tbody></table></div>{target && <ConfirmDialog title={target.role === "admin" ? "Promote to administrator?" : "Remove administrator access?"} message={target.user.id === currentUserId ? "You are changing your own administrator access. If another administrator exists, you will immediately lose access to these pages. The database will refuse the change if you are the final administrator." : `${target.user.full_name} will ${target.role === "admin" ? "gain access to instruments, all bookings, users, exports, and audit records" : "lose all administrator access"}.`} confirmLabel={target.role === "admin" ? "Promote user" : "Demote administrator"} dangerous={target.role === "user"} pending={pending} onClose={() => setTarget(undefined)} onConfirm={() => startTransition(async () => { const result = await changeUserRole(target.user.id, target.role, true); if (result.success) { setMessage(result.message); setTarget(undefined); router.refresh(); } else setError(result.message); })} />}</>;
}
