"use server";
import { headers } from "next/headers";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
export type AuthState = { status: "idle" | "error" | "success"; message: string };
function friendlyAuthError(message: string) { const value = message.toLowerCase(); if (value.includes("invalid login credentials")) return "Email or password is incorrect."; if (value.includes("already registered") || value.includes("already exists")) return "An account with this email already exists."; if (value.includes("password")) return "Password must meet the security requirements (at least 8 characters)."; if (value.includes("rate") || value.includes("too many")) return "Too many attempts. Please wait and try again."; return "Authentication could not be completed. Please try again."; }
export async function signIn(_: AuthState, formData: FormData): Promise<AuthState> { const email = String(formData.get("email") ?? "").trim(); const password = String(formData.get("password") ?? ""); if (!email || !password) return { status: "error", message: "Enter your email and password." }; const supabase = await createClient(); const { error } = await supabase.auth.signInWithPassword({ email, password }); if (error) return { status: "error", message: friendlyAuthError(error.message) }; redirect("/dashboard"); }
export async function signUp(_: AuthState, formData: FormData): Promise<AuthState> { const fullName = String(formData.get("fullName") ?? "").trim(); const email = String(formData.get("email") ?? "").trim(); const password = String(formData.get("password") ?? ""); if (fullName.length < 2) return { status: "error", message: "Enter your full name." }; if (!email || password.length < 8) return { status: "error", message: "Use a valid email and a password of at least 8 characters." }; const origin = (await headers()).get("origin"); const supabase = await createClient(); const { data, error } = await supabase.auth.signUp({ email, password, options: { data: { full_name: fullName }, emailRedirectTo: origin ? `${origin}/auth/callback` : undefined } }); if (error) return { status: "error", message: friendlyAuthError(error.message) }; if (data.session) redirect("/dashboard"); return { status: "success", message: "Account created. Check your email to confirm your address, then sign in." }; }
export async function signOut() { const supabase = await createClient(); await supabase.auth.signOut(); redirect("/login"); }
